const state={route:location.hash.slice(1)||'today',portfolio:'top10'};
const nav=[['today','Today'],['tracker','Tracker'],['data','Data'],['method','Method']];
let D={checkpoints_et:['08:17','11:17','17:17','20:17'],aggregate:{top10:{},top20:{}},snapshots:[]};
try{const r=await fetch('/data/index.json',{cache:'no-store'});if(r.ok)D=await r.json()}catch(e){console.error(e)}
addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'today';render()});
const pct=v=>v==null?'—':`${v>=0?'+':''}${(v*100).toFixed(1)}%`;
const units=v=>v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}u`;
const odds=v=>v==null?'—':v>0?`+${v}`:`${v}`;
const safe=v=>v==null?'—':String(v);
function layout(body){return `<div class="shell"><header class="top"><div><div class="brand">HR <span>Form Board</span> <span class="pill">GitHub Actions edition</span></div><div class="muted">Independent from ChatGPT Scheduled Tasks</div></div><nav>${nav.map(([r,l])=>`<a class="nav ${state.route===r?'active':''}" href="#${r}">${l}</a>`).join('')}</nav></header>${body}<footer class="footer">Odds can change. Missing prices are marked unavailable or unverified and are never inferred. One-unit flat staking is used for tracking.</footer></div>`}
function metrics(s={}){return `<div class="grid"><div class="card"><div class="metric"><strong>${s.wins||0}–${s.losses||0}${s.pushes?`–${s.pushes}P`:''}</strong><span>Record</span></div></div><div class="card"><div class="metric"><strong>${pct(s.hit_rate)}</strong><span>Hit rate</span></div></div><div class="card"><div class="metric"><strong>${units(s.net_units||0)}</strong><span>Net units</span></div></div><div class="card"><div class="metric"><strong>${pct(s.roi)}</strong><span>ROI</span></div></div></div>`}
function portfolioTabs(){return `<div class="tabs"><button data-p="top10" class="${state.portfolio==='top10'?'active':''}">Top 10</button><button data-p="top20" class="${state.portfolio==='top20'?'active':''}">Top 20</button></div>`}
function bindTabs(){document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.portfolio=b.dataset.p;render()})}
function rows(picks=[]){return picks.map(p=>`<tr><td>${safe(p.rank)}</td><td><b>${safe(p.player)}</b></td><td>${Number(p.score||0).toFixed(4)}</td><td>${safe(p.hr_games_l5)} / ${safe(p.hr_games_l7)} / ${safe(p.hr_games_l15)}</td><td class="plus">${odds(p.odds??p.best_odds)}</td><td>${safe(p.sportsbook??p.best_sportsbook)}</td><td>${p.dk_odds==null?'Unverified':odds(p.dk_odds)}</td><td>${safe(p.game_time_et)}</td><td><span class="${p.result==='WIN'?'win':p.result==='LOSS'?'loss':''}">${safe(p.result||'PENDING')}</span></td><td>${p.profit_units==null?'—':units(p.profit_units)}</td></tr>`).join('')}
function table(picks=[]){return picks.length?`<div class="tablewrap"><table><thead><tr><th>#</th><th>Player</th><th>Score</th><th>L5/L7/L15</th><th>Best odds</th><th>Best sportsbook</th><th>DK</th><th>Game ET</th><th>Result</th><th>P/L</th></tr></thead><tbody>${rows(picks)}</tbody></table></div>`:'<div class="empty">No selections were frozen for this portfolio.</div>'}
function snapshotsDesc(){return [...(D.snapshots||[])].sort((a,b)=>`${b.slate_date}_${b.checkpoint_et}`.localeCompare(`${a.slate_date}_${a.checkpoint_et}`))}
function latestSlate(){const snaps=snapshotsDesc();return snaps.length?snaps[0].slate_date:null}
function todayPage(){const checks=D.checkpoints_et||['08:17','11:17','17:17','20:17'];const latest=latestSlate();const todays=snapshotsDesc().filter(s=>s.slate_date===latest);const agg=D.aggregate?.[state.portfolio]||{};return layout(`<section class="hero"><div class="card"><div class="eyebrow">Cloud-run free tracker</div><h1>Today’s frozen<br>HR form board.</h1><p class="muted">Four ET checkpoints calculate corrected cumulative form, verify eligible 1+ HR prices, label the best sportsbook, and preserve separate Top 10 and Top 20 portfolios.</p><div class="notice"><b>Schedule:</b> 8:17 AM, 11:17 AM, 5:17 PM and 8:17 PM ET. Your computer does not need to be on.</div></div><div class="card"><h2>All-time ${state.portfolio==='top10'?'Top 10':'Top 20'}</h2>${portfolioTabs()}${metrics(agg)}</div></section><section class="card section"><div class="eyebrow">Today</div><h2>${latest?`Slate ${latest}`:'Checkpoint status'}</h2><div class="grid4">${checks.map(c=>{const s=todays.find(x=>x.checkpoint_et===c);const pf=s?.portfolios?.[state.portfolio];return `<div class="card checkpoint"><h2>${c} ET</h2>${s?`<p><span class="pill">${safe(s.status)}</span></p><p class="muted">Captured ${safe(s.observed_at_et)}</p><p><b>${pf?.picks?.length||0}</b> frozen selections</p>`:'<p><span class="pill">Pending</span></p><p class="muted">No immutable snapshot has been committed for this checkpoint.</p>'}</div>`}).join('')}</div></section>${todays.length?`<section class="card section"><div class="eyebrow">Latest available checkpoint</div><h2>${todays[0].slate_date} · ${todays[0].checkpoint_et} ET</h2>${table(todays[0].portfolios?.[state.portfolio]?.picks||[])}</section>`:'<section class="card section"><div class="empty">No Action-generated snapshot has been committed yet.</div></section>'}`)}
function trackerPage(){const snaps=snapshotsDesc();const agg=D.aggregate?.[state.portfolio]||{};return layout(`<section class="card"><div class="eyebrow">Tracked performance</div><h2>${state.portfolio==='top10'?'Top 10':'Top 20'} portfolio</h2>${portfolioTabs()}${metrics(agg)}</section><section class="card section"><div class="eyebrow">Immutable checkpoint ledger</div><h2>All tracked snapshots</h2>${snaps.length?snaps.map(s=>{const pf=s.portfolios?.[state.portfolio];return `<article class="card section"><h2>${s.slate_date} · ${s.checkpoint_et} ET</h2><p class="muted">Status: ${safe(s.status)} · Captured ${safe(s.observed_at_et)}</p>${pf?metrics(pf.summary||{}):'<div class="notice">No portfolio was frozen at this checkpoint.</div>'}${table(pf?.picks||[])}</article>`}).join(''):'<div class="empty">No tracked snapshots yet.</div>'}</section>`)}
function dataPage(){const snaps=snapshotsDesc();return layout(`<section class="grid2"><div class="card"><div class="eyebrow">Odds data</div><h2>Verified price recovery</h2><p class="muted">Vegas Insider comparison rows are parsed by sportsbook where identifiable. Official DraftKings public 1+ HR rows are matched independently. The highest verified eligible price is preserved with its source and capture time.</p></div><div class="card"><div class="eyebrow">MLB data</div><h2>Form and settlement</h2><p class="muted">MLB player IDs, schedules and prior PA-games produce the cumulative form score. Official game logs settle each frozen selection after the game is final.</p></div></section><section class="card section"><h2>Validation gates</h2><table><tbody><tr><td>Checkpoint captured at a scheduled ET time</td><td class="plus">Required</td></tr><tr><td>Game has not started</td><td class="plus">Required</td></tr><tr><td>At least 15 prior PA-games</td><td class="plus">Required</td></tr><tr><td>Correct cumulative L5/L7/L15 score</td><td class="plus">Required</td></tr><tr><td>Best verified 1+ HR price at +500 or longer</td><td class="plus">Required</td></tr><tr><td>Sportsbook and capture timestamp preserved</td><td class="plus">Required</td></tr><tr><td>Top 10 and Top 20 histories</td><td class="plus">Separate</td></tr><tr><td>Unavailable DraftKings price</td><td class="plus">Marked unverified</td></tr></tbody></table></section><section class="card section"><div class="eyebrow">Source log</div><h2>Checkpoint source status</h2>${snaps.length?`<div class="tablewrap"><table><thead><tr><th>Slate</th><th>Checkpoint</th><th>Status</th><th>Vegas Insider date</th><th>DK rows</th><th>Captured ET</th></tr></thead><tbody>${snaps.map(s=>`<tr><td>${safe(s.slate_date)}</td><td>${safe(s.checkpoint_et)}</td><td>${safe(s.status)}</td><td>${safe(s.sources?.vegas_insider?.source_date)}</td><td>${safe(s.sources?.draftkings?.rows??0)}</td><td>${safe(s.observed_at_et)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No source runs have been committed yet.</div>'}</section>`)}
function methodPage(){return layout(`<section class="hero"><div class="card"><div class="eyebrow">Locked benchmark</div><h2>Cumulative form score</h2><p><b>Score = 0.50 × (HR games L5 ÷ 5) + 0.30 × (HR games L7 ÷ 7) + 0.20 × (HR games L15 ÷ 15).</b></p><p class="muted">The L7 window includes the L5 games, and the L15 window includes the L7 games. A multi-HR game counts as one HR game for the ranking signal.</p></div><div class="card"><div class="eyebrow">Eligibility</div><h2>Price after form</h2><p class="muted">Players are ranked by form first. Odds are applied afterward. Only players with at least 15 prior PA-games, an unstarted game, and a best verified 1+ HR price of +500 or longer are eligible.</p></div></section><section class="grid2 section"><div class="card"><h2>Four immutable checks</h2><p>8:17 AM, 11:17 AM, 5:17 PM and 8:17 PM ET. Later checkpoints cover the remaining unstarted slate and never overwrite earlier selections.</p></div><div class="card"><h2>Separate portfolios</h2><p>Top 10 and Top 20 each maintain their own record, units, ROI, hit rate and checkpoint history even though the Top 10 is contained within the Top 20.</p></div><div class="card"><h2>Sportsbook labeling</h2><p>The selected row stores DraftKings odds when verified, all other identifiable prices, the best sportsbook, the winning price, and the capture timestamp. Unknown book headers remain explicitly unidentified.</p></div><div class="card"><h2>Settlement</h2><p>Every pick is tracked at one flat unit. A win earns American-odds profit, a loss loses one unit, and postponed or unresolved games remain pending until official MLB data settles them.</p></div></section>`)}
function render(){const page={today:todayPage,tracker:trackerPage,data:dataPage,method:methodPage}[state.route]||todayPage;document.querySelector('#app').innerHTML=page();bindTabs()}
render();
