const state={route:location.hash.slice(1)||'today',portfolio:'top10'};
const nav=[['today','Today'],['tracker','Tracker'],['data','Data'],['method','Method']];
let D={checkpoints_et:['08:17','11:17','17:17','20:17'],aggregate:{top10:{},top20:{}},latest:null,snapshots:[]};
try{const r=await fetch('/data/index.json',{cache:'no-store'});if(r.ok)D=await r.json()}catch(e){console.error(e)}
addEventListener('hashchange',()=>{state.route=location.hash.slice(1)||'today';render()});
const safe=v=>v==null||v===''?'—':String(v),odds=v=>v==null?'—':v>0?`+${v}`:`${v}`,pct=v=>v==null?'—':`${v>=0?'+':''}${(v*100).toFixed(1)}%`,units=v=>v==null?'—':`${v>=0?'+':''}${Number(v).toFixed(2)}u`;
function layout(body){return `<div class="shell"><header class="top"><div><div class="brand">HR <span>Form Board</span> <span class="pill">GitHub Actions edition</span></div><div class="muted">Independent from ChatGPT Scheduled Tasks</div></div><nav>${nav.map(([r,l])=>`<a class="nav ${state.route===r?'active':''}" href="#${r}">${l}</a>`).join('')}</nav></header>${body}<footer class="footer">Prices come only from the user-owned MLB HR Edge database. This site does not call SportsGameOdds or sportsbook sites.</footer></div>`}
function metrics(s={}){return `<div class="grid"><div class="card"><div class="metric"><strong>${s.wins||0}–${s.losses||0}${s.pushes?`–${s.pushes}P`:''}</strong><span>Record</span></div></div><div class="card"><div class="metric"><strong>${pct(s.hit_rate)}</strong><span>Hit rate</span></div></div><div class="card"><div class="metric"><strong>${units(s.net_units||0)}</strong><span>Net units</span></div></div><div class="card"><div class="metric"><strong>${pct(s.roi)}</strong><span>ROI</span></div></div></div>`}
function tabs(){return `<div class="tabs"><button data-p="top10" class="${state.portfolio==='top10'?'active':''}">Top 10</button><button data-p="top20" class="${state.portfolio==='top20'?'active':''}">Top 20</button></div>`}
function bind(){document.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{state.portfolio=b.dataset.p;render()})}
function ordered(){return [...(D.snapshots||[])].sort((a,b)=>`${b.slate_date}_${b.checkpoint_et}`.localeCompare(`${a.slate_date}_${a.checkpoint_et}`))}
function sourceOf(x){return x?.sources?.mlb_hr_edge||{}}
function allPrices(p){return (p.all_prices||[]).map(x=>`${safe(x.book)} ${odds(x.odds)} @ ${safe(x.captured_at)}`).join(' | ')||'—'}
function rows(picks=[]){return picks.map(p=>`<tr><td>${safe(p.rank)}</td><td><b>${safe(p.player)}</b><div class="muted">${safe(p.batter_team)} · ${safe(p.opponent)}</div></td><td>${Number(p.score||0).toFixed(4)}</td><td>${safe(p.hr_games_l5)} / ${safe(p.hr_games_l7)} / ${safe(p.hr_games_l15)}</td><td class="plus">${odds(p.odds)}</td><td>${safe(p.sportsbook)}</td><td>${p.dk_odds==null?'Unavailable':odds(p.dk_odds)}</td><td>${safe(p.game_time_et)}</td><td>${safe(p.result)}</td><td>${safe(p.best_price_captured_at)}</td><td>${allPrices(p)}</td></tr>`).join('')}
function table(picks=[]){return picks.length?`<div class="tablewrap"><table><thead><tr><th>#</th><th>Player</th><th>Score</th><th>L5/L7/L15</th><th>Best odds</th><th>Best book</th><th>DK</th><th>Game ET</th><th>Status</th><th>Captured</th><th>All shared prices</th></tr></thead><tbody>${rows(picks)}</tbody></table></div>`:'<div class="empty">No eligible players are currently available.</div>'}
function latestSection(){const l=D.latest,s=sourceOf(l),p=l?.portfolios?.[state.portfolio];if(!l)return `<section class="card section"><div class="eyebrow">Latest MLB HR Edge slate</div><h2>Refresh pending</h2><div class="empty">No latest-slate refresh has been committed yet.</div></section>`;return `<section class="card section"><div class="eyebrow">Current board · not added to tracked results</div><h2>Latest MLB HR Edge slate: ${safe(l.slate_date)}</h2><p><span class="pill">${safe(l.status)}</span></p><p class="muted">HR Edge capture: ${safe(s.generated_at)} · Form Board refresh: ${safe(l.refreshed_at_et)} · Shared rows: ${safe(s.row_count??0)} · Eligible: ${safe(l.eligible_candidates??0)}</p>${table(p?.picks||[])}</section>`}
function todayPage(){const snaps=ordered(),date=snaps[0]?.slate_date,todays=snaps.filter(x=>x.slate_date===date),agg=D.aggregate?.[state.portfolio]||{};return layout(`<section class="hero"><div class="card"><div class="eyebrow">Current + tracked</div><h1>Latest shared<br>HR form board.</h1><p class="muted">The current panel uses the newest persisted MLB HR Edge slate. Scheduled checkpoints remain immutable and are tracked separately.</p><div class="notice"><b>Shared fetches:</b> 8:17 AM, 11:17 AM, 5:17 PM and 8:17 PM ET.</div></div><div class="card"><h2>Tracked ${state.portfolio==='top10'?'Top 10':'Top 20'}</h2>${tabs()}${metrics(agg)}</div></section>${latestSection()}<section class="card section"><div class="eyebrow">Immutable checkpoint status</div><h2>${date?`Tracked slate ${date}`:'No tracked slate yet'}</h2><div class="grid4">${(D.checkpoints_et||[]).map(c=>{const s=todays.find(x=>x.checkpoint_et===c),p=s?.portfolios?.[state.portfolio];return `<div class="card checkpoint"><h2>${c} ET</h2>${s?`<p><span class="pill">${safe(s.status)}</span></p><p><b>${p?.picks?.length||0}</b> frozen selections</p>`:'<p><span class="pill">Pending</span></p>'}</div>`}).join('')}</div></section>`)}
function trackerPage(){const agg=D.aggregate?.[state.portfolio]||{},snaps=ordered();return layout(`<section class="card"><div class="eyebrow">Tracked performance only</div><h2>${state.portfolio==='top10'?'Top 10':'Top 20'} portfolio</h2>${tabs()}${metrics(agg)}</section><section class="card section"><h2>Immutable checkpoint ledger</h2>${snaps.length?snaps.map(s=>{const p=s.portfolios?.[state.portfolio],src=sourceOf(s);return `<article class="card section"><h2>${safe(s.slate_date)} · ${safe(s.checkpoint_et)} ET</h2><p class="muted">${safe(s.status)} · Source ${safe(src.generated_at)} · As-of ${safe(src.as_of)}</p>${p?metrics(p.summary||{}):''}${table(p?.picks||[])}</article>`}).join(''):'<div class="empty">No tracked snapshots yet.</div>'}</section>`)}
function dataPage(){const l=D.latest,s=sourceOf(l);return layout(`<section class="grid2"><div class="card"><div class="eyebrow">Market source</div><h2>MLB HR Edge only</h2><p class="muted">The Actions site reads the newest persisted FanDuel, DraftKings and BetMGM slate from MLB HR Edge. It makes no direct provider request.</p></div><div class="card"><div class="eyebrow">Latest source state</div><h2>${safe(l?.slate_date)}</h2><p class="muted">Status ${safe(l?.status)} · Source capture ${safe(s.generated_at)} · Rows ${safe(s.row_count??0)}</p></div></section><section class="card section"><h2>Data rules</h2><table><tbody><tr><td>Latest board is informational/current</td><td class="plus">Not tracked</td></tr><tr><td>Scheduled checkpoint portfolios</td><td class="plus">Immutable</td></tr><tr><td>Exact MLB batter and game IDs</td><td class="plus">Required</td></tr><tr><td>At least 15 prior PA-games</td><td class="plus">Required</td></tr><tr><td>Unstarted game</td><td class="plus">Required</td></tr><tr><td>Best shared price at +500 or longer</td><td class="plus">Required</td></tr></tbody></table></section>`)}
function methodPage(){return layout(`<section class="hero"><div class="card"><div class="eyebrow">Locked formula</div><h2>Cumulative form score</h2><p><b>Score = 0.50 × (HR games L5 ÷ 5) + 0.30 × (HR games L7 ÷ 7) + 0.20 × (HR games L15 ÷ 15).</b></p><p class="muted">L7 contains L5 and L15 contains L7. A multi-HR game counts as one HR game.</p></div><div class="card"><div class="eyebrow">Two views</div><h2>Current versus tracked</h2><p class="muted">Today shows the newest MLB HR Edge slate. Tracker contains only frozen scheduled checkpoints used for performance accounting.</p></div></section>`)}
function render(){document.querySelector('#app').innerHTML=({today:todayPage,tracker:trackerPage,data:dataPage,method:methodPage}[state.route]||todayPage)();bind()}
render();
